## Day Objectives:
#### Functional Programming
##### List comprehension
#### Iterators and Generators
#### Map
#### Filter
##### Lambda

In [30]:
## List comprehension
# List Comprehension is very easy way to create lists and more effective
## Compared with for loop
# Program using List Comprehension
n=10
li=[]
for i in range(1,n+1):
    li.append(i)
print(li)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [31]:
## Using list comprehension
li=[i for i in range(1,11)]
li

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
## k=[10,20,5]
## k^2=[]

In [32]:
## Cubes
li=[i**3 for i in li]
li

[1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]

In [4]:
## Factorial
def factorial(n):
    if n==0 or n==1:
        return 1
    else:
        return n * factorial(n-1)
factorial(6)

720

In [9]:
## Cumulative sum
#n=5->[1,3,6,10,15]
n = 6
cumulativeSum=[sum(range(1,i+1)) for i in range(1,n+1)]
cumulativeSum

[1, 3, 6, 10, 15, 21]

In [16]:
## List Comprehension to check leap Year
st=1970
et=2020
leapyear=[i  for  i  in  range(st,et+1)
          if (i%400==0) or (i %100!=0 and i%4==0)]
leapyear

[1972, 1976, 1980, 1984, 1988, 1992, 1996, 2000, 2004, 2008, 2012, 2016, 2020]

In [19]:
## Iterators
# iterator is an object that contains number of elements.
# 2-methods
# iter()
# next()
# All ds are all iterable objects

In [40]:
def cumulativesum(n):
    sum=0
    li=[]
    for i in range(1,n+1):
        sum=sum+i
        print(sum)
        li.append(sum)
    print(li)
cumulativesum(5)

1
3
6
10
15
[1, 3, 6, 10, 15]


In [22]:
it='python'
it=iter('python')
print(it)

In [ ]:
a='pythonprogram'

In [43]:
it='python'
for i in it:
    print(i)

p
y
t
h
o
n


In [23]:
print(next(it))

p


In [24]:
print(next(it))

y


In [25]:
print('1: ')
print(next(it))
print('2: ',next(it))

1: 
t
2:  h


In [26]:
## Generators
# Generator is a function.we can create iterators using Generators.
# In other words Generator is a function which returns Iterable objects
# It uses "yield" instead of return

In [45]:
def generatorfunction():
    yield 1
    yield 2
    yield 3
generatorfunction()
for value in generatorfunction():
    print(value)

1
2
3


In [29]:
## Sqaure of a numbers up to given range
def gen():
    n=2
    while True:
        n**=2
        yield n
a=gen()
for i in range(5):
    print(next(a))

4
16
256
65536
4294967296


In [ ]:
## maps in python
# it produces a list of results that it apply given function to each item
# of a iterable object
def addition(n):

### NUMPY


- Numpy is a python library and a fundamental package for scientific computing in Python
- It is used to create multidimensional arrays for fast operations. 
- Use the following import conversion to access numpy library .
- import numpy as np
- NumPy have a fixed size of arrays used to store a collection of elements, unlike python lists.


In [4]:
# Creating 1D array using numpy
import numpy as np
array_1d=np.array([2,4,5,6,7,9])
print(array_1d)
type(array_1d)

[2 4 5 6 7 9]


numpy.ndarray

In [3]:
# Creating 2D array using numpy
import numpy as np
array_2d = np.array([[2,3,4],[5,7,8]])
print(array_2d)

[[2 3 4]
 [5 7 8]]


In [5]:
# program to print the given list in to an array
import numpy as np
li = [1,2,3,'z']
a = np.array(li)
print(a)


['1' '2' '3' 'z']


- If the size of the array is large to type, we can simply use array range called "arange"

In [6]:
# example
# To print 1D array between 1 to 15
import numpy as np
a = np.arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [7]:
import numpy as np
a2=np.arange(100).reshape(10,10)
a2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [8]:
import numpy as np
a3=np.arange(50).reshape(25,2)
a3

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39],
       [40, 41],
       [42, 43],
       [44, 45],
       [46, 47],
       [48, 49]])

In [9]:
import numpy as np
a3=np.arange(50).reshape(2,25)
a3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [10]:
import numpy as np
x = np.zeros((3,2))
print(x)


[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [11]:
#give space of 2
np.arange(3,10,2)

array([3, 5, 7, 9])

In [12]:
import numpy as np
x = np.ones((3,2))
print(x)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.full((3,3),2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [15]:
#all floating value converted into intigers
np.full((3,3),2.2,dtype=np.int)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [16]:
# diagonal
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [18]:
# horizontally(rows) 3 lines filled with f[list],vertically 1 line (column)
f=np.array([1,2,3])
np.tile(f,(3,1))

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [19]:
# i want 2 to 50 random value
50*np.random.random() +2

4.801793409465586

In [20]:
# i want 2 to 50 random value
50*np.random.random() +3

44.215136705076574

In [21]:
# Create a matrix of random value
np.random.random([3,3])

array([[0.41002089, 0.42100964, 0.7245558 ],
       [0.45158659, 0.08873131, 0.400631  ],
       [0.73807607, 0.97766864, 0.44159166]])

In [22]:
# I want print 1 to 50 but these range equally disturbed into 100 parts
a=np.linspace(1,50,100)

In [25]:
# I want print 1 to 50 but these range equally disturbed into 100 parts
a=np.linspace(1,10,20)
a

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [26]:
a.itemsize

8

##### PANDAS

- Pandas basically use for data analysis.It is bulid on top of Numpy only
- We will mostly be using this pandas package a lot
- In fact if you are going to use it heavily for any data manipulation,any sort of data analysis and any sort of datavisualization ,and any sort of Mechine Learning model building ##### DataVisualization.

In [28]:
import numpy as np
temp=np.random.randint(low=20,high=100,size=[20])
temp

array([77, 86, 63, 47, 86, 88, 60, 62, 42, 46, 70, 87, 37, 76, 78, 69, 34,
       44, 49, 83])

In [30]:
name=np.random.choice(['ravi','kishore','anil','kumar'],20)
name

array(['anil', 'anil', 'kumar', 'anil', 'kumar', 'ravi', 'ravi', 'anil',
       'kumar', 'anil', 'anil', 'ravi', 'anil', 'kishore', 'kumar',
       'kishore', 'kishore', 'kishore', 'kishore', 'anil'], dtype='<U7')

In [31]:
import turtle as t
wn=turtle.screen()
t1=t.turtle()
t1.forward(90)
wn.mainloop()

NameError: name 'turtle' is not defined

In [ ]:
## Data Visualization using matplotlib
